export enum NogiMember {
  Akimoto_Manatsu = "秋元真夏",
  Saito_Asuka = "齋藤飛鳥",
  Higuchi_Hina = "樋口日奈",
  Wada_Maaya = "和田まあや",

  Kitano_Hinako = "北野日奈子",
  Shinuchi_Mai = "新内眞衣",
  Suzuki_Ayane = "鈴木絢音",
  Yamazaki_Rena = "山崎怜奈",

  Ito_Riria = "伊藤理々杏",
  Iwamoto_Renka = "岩本蓮加",
  Umezawa_Minami = "梅澤美波",
  Kubo_Shiori = "久保史緒里",
  Sakaguchi_Tamami = "阪口珠美",
  Sato_Kaede = "佐藤楓",
  Nakamura_Reno = "中村麗乃",
  Mukai_Hazuki = "向井葉月",
  Yamashita_Mizuki = "山下美月",
  Yoshida_AyanoChristie = "吉田綾乃ｸﾘｽﾃｨｰ",
  Yoda_Yuuki = "与田祐希",

  Endo_Sakura = "遠藤さくら",
  Kaki_Haruka = "賀喜遥香",
  Kakehashi_Sayaka = "掛橋沙耶香",
  Kanagawa_Saya = "金川紗耶",
  Kitagawa_Yuri = "北川悠理",
  Kuromi_Haruka = "黒見明香",
  Sato_Rika = "佐藤璃果",
  Shibata_Yuna = "柴田柚菜",
  Seimiya_Rei = "清宮レイ",
  Tamura_Mayu = "田村真佑",
  Tsutsui_Ayame = "筒井あやめ",
  Hayakawa_Seira = "早川聖来",
  Hayashi_Runa = "林瑠奈",
  Matsuo_Miyu = "松尾美佑",
  Yakubo_Mio = "矢久保美緒",
  Yumiki_Nao = "弓木奈於",

  Ioki_Mao = "五百城茉央",
  Ikeda_Teresa = "池田瑛紗",
  Ichinose_Miku = "一ノ瀬美空",
  Inoue_Nagi = "井上和",
  Ogawa_Aya = "小川彩",
  Okuda_Iroha = "奥田いろは",
  Kawasaki_Sakura = "川﨑桜",
  Sugawara_Satsuki = "菅原咲月",
  Tomisato_Nao = "冨里奈央",
  Nakanishi_Aruno = "中西アルノ",
}